In [22]:
# Киселева Ксения 5030102/30002
import numpy as np
import sys
import array

# типы данных Python

x = 1
print (type(x))
print (sys.getsizeof(x))

x = 'hello'
print (type(x))

x = True
print (type(x))

l1 = list([])
print (sys.getsizeof(l1))

l2 = list([1,2,3])
print (sys.getsizeof(l2))

l3 = list([1,"2",True])
print (sys.getsizeof(l3))

al = array.array('i',[1,2,3]) # i - работаем только с int
print (sys.getsizeof(al))
print(type(al))

<class 'int'>
28
<class 'str'>
<class 'bool'>
56
88
88
92
<class 'array.array'>


In [32]:
a = np.array([1,2,3,4,5])
print(type(a), a)

a = np.array([1.23, 2, 3, 4, 5]) #повышающее приведение типов
print(type(a), a)

a = np.array([1.23, 2, 3, 4, 5], dtype=int) #к опред. типу
print(type(a), a)

a = np.array([range(i, i+3) for i in [2, 4, 6]])
print(a, type(a))

a = np.zeros(10, dtype=int)
print(a, type(a))

print(np.ones((3, 5), dtype=float))

print(np.full((4, 5), 3.1415))

print(np.arange(0, 20, 2)) # диапазон от 0 до 20-1 с шагом 2

print(np.eye(4)) # Е матрица

<class 'numpy.ndarray'> [1 2 3 4 5]
<class 'numpy.ndarray'> [1.23 2.   3.   4.   5.  ]
<class 'numpy.ndarray'> [1 2 3 4 5]
[[2 3 4]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]
[ 0  2  4  6  8 10 12 14 16 18]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
np.random.seed(1) #установка н.з. (случ. числа в одном и том же порядке)

x1 = np.random.randint(10, size=3)
print(x1)

x2 = np.random.randint(10, size=(3, 2))
print(x2)

x3 = np.random.randint(10, size=(3, 2, 1))
print(x3)

print(x1.ndim, x1.shape, x1.size) # ndim - число размерностей, shape - размер каждой размерности 
# size - общий размер массива
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

[5 8 9]
[[5 0]
 [0 1]
 [7 6]]
[[[9]
  [2]]

 [[4]
  [5]]

 [[2]
  [4]]]
1 (3,) 3
2 (3, 2) 6
3 (3, 2, 1) 6


In [56]:
a = np.array([1,2,3, 4, 5])
print(a[0])
print(a[-2]) # с конца с -1 

a[1] = 20
print(a)

a = np.array([[1, 2], [3, 4]])
print(a)
print(a[0,0])
print(a[-1,-1])

a[1, 0] = 100
print(a)

a = np.array([1,2,3,4])
b = np.array([1.0,2,3,4])
print(a)
print(b)

a[0] = 10
print(a) 

a[0] = 10.123 # приведет к int (НЕТ ИЗМЕНЕНИЯ ТИПОВ)
print(a) 

1
4
[ 1 20  3  4  5]
[[1 2]
 [3 4]]
1
4
[[  1   2]
 [100   4]]
[1 2 3 4]
[1. 2. 3. 4.]
[10  2  3  4]
[10  2  3  4]


In [70]:
# Срез [нач.эл:кон.эл^(-1):шаг] [0:конец:1]
a = np.array([1, 2, 3, 4, 5, 6])
print(a[:3]) #[0:3:1]
print(a[3:])
print(a[1:5]) 
print(a[1:6:2])
print(a[1::2])

print(a[::-1]) # обр. порядок

[1 2 3]
[4 5 6]
[2 3 4 5]
[2 4 6]
[2 4 6]
[6 5 4 3 2 1]


In [84]:
a = np.arange(1,13)
print(a)
print(a.reshape(2,6)) #меняет размерность (превратится в 2 стр по 6 эл)

x = np.array([1, 2, 3])
y = np.array([4, 5]) 
z = np.array([6])
print(np.concatenate([x, y, z])) #объединение в 1 строчку [эл., ]

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
r1 = np.vstack([x, y]) # ставится один на другой, вертикальное склеивание
print(r1)
print(np.hstack((r1, r1))) # склеиваются сбоку (построчно)
#метод dstack - ставит один массив за другой 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [90]:
x = np.arange(10)
print(x)

print(x*2 + 1)

print(np.multiply(x, 2)) #*
print(np.add(np.multiply(x, 2), 1)) #*+

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]


In [106]:
x = np.arange(5)
y = np.empty(5)
print(np.multiply(x,10))

print(np.multiply(x, 10, out=y)) # out - куда записать результат
print(y)

y2 = np.zeros(10)
print(np.multiply(x, 10, out=y2[::2]))
print(y2)

x = np.arange(1, 5)
print(x)

print(np.add.reduce(x)) #- сернуть все числа к одному ( сумма)

print(np.add.accumulate(x)) #- поэтапное сложение в массив

x = np.arange(1, 10)
print(np.add.outer(x, x)) #- сложение попарно ( как табл. умножения (multiply) только сложение)

[ 0 10 20 30 40]
[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]
[1 2 3 4]
10
[ 1  3  6 10]
[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
