In [4]:
# 1. Привести различные способы создания объектов типа Series
# Для создания Series можно использовать
# - списки Python или массивы NumPy
# - скалярные значение
# - словари

import pandas as pd
import numpy as np

# Из списка Python
data_list = [1, 2, 3, 4, 5]
series_from_list = pd.Series(data_list)
print(series_from_list)

# Из массива NumPy
data_array = np.array([10, 20, 30, 40])
series_from_array = pd.Series(data_array)
print(series_from_array)

# Создание Series из скалярного значения
scalar_value = 5
series_from_scalar = pd.Series(scalar_value, index=[0, 1, 2, 3, 4])
print(series_from_scalar)

# Из словаря
data_dict = {'a': 1, 'b': 2, 'c': 3}
series_from_dict = pd.Series(data_dict)
print(series_from_dict)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    10
1    20
2    30
3    40
dtype: int32
0    5
1    5
2    5
3    5
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64


In [8]:
# 2. Привести различные способы создания объектов типа DataFrame
# DataFrame. Способы создания
# - через объекты Series
# - списки словарей
# - словари объектов Series
# - двумерный массив NumPy
# - структурированный массив Numpy

# Создание Series
s1 = pd.Series([1, 2, 3], name='A')
s2 = pd.Series([4, 5, 6], name='B')

# Создание DataFrame из Series
df_from_series = pd.DataFrame({s1.name: s1, s2.name: s2})
print(df_from_series)

# Список словарей
data_list_of_dicts = [
    {'A': 1, 'B': 4},
    {'A': 2, 'B': 5},
    {'A': 3, 'B': 6}
]

# Создание DataFrame через списки словарей
df_from_list_of_dicts = pd.DataFrame(data_list_of_dicts)
print(df_from_list_of_dicts)

# Словарь объектов Series
data_dict_of_series = {
    'A': pd.Series([1, 2, 3]),
    'B': pd.Series([4, 5, 6])
}

# Создание DataFrame через словари объктов Series
df_from_dict_of_series = pd.DataFrame(data_dict_of_series)
print(df_from_dict_of_series)

import numpy as np

# Двумерный массив NumPy
data_array_2d = np.array([[1, 4], [2, 5], [3, 6]])

# Создание DataFrame через Двумерный массив NumPy
df_from_array_2d = pd.DataFrame(data_array_2d, columns=['A', 'B'])
print(df_from_array_2d)

# Структурированный массив NumPy
structured_array = np.array([(1, 4), (2, 5), (3, 6)], dtype=[('A', 'i4'), ('B', 'i4')])

# Создание DataFrame через Структурированный массив NumPy
df_from_structured_array = pd.DataFrame(structured_array)
print(df_from_structured_array)


   A  B
0  1  4
1  2  5
2  3  6
   A  B
0  1  4
1  2  5
2  3  6
   A  B
0  1  4
1  2  5
2  3  6
   A  B
0  1  4
1  2  5
2  3  6
   A  B
0  1  4
1  2  5
2  3  6


In [10]:
# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы вместо NaN было установлено значение 1

# Создание двух объектов Series с неодинаковыми индексами
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([40, 50], index=['b', 'd'])

# Объединение Series с заменой NaN на 1
combined_series = s1.add(s2, fill_value=1)

print(combined_series)


a    11.0
b    60.0
c    31.0
d    51.0
dtype: float64


In [12]:
# 4. Переписать пример с транслирование для DataFrame так, чтобы вычитание происходило по СТОЛБЦАМ

# Генерация случайных данных
rng = np.random.default_rng(1)
a = rng.integers(0, 10, (3, 4))
print("Сгенерированный массив:")
print(a)

# Печать первой строки массива
print("\nПервая строка массива:")
print(a[0])

# Вычитание первой строки из всего массива
print("\nРезультат вычитания первой строки из всего массива:")
print(a - a[0])

# Создание DataFrame
df = pd.DataFrame(a, columns=['a', 'b', 'c', 'd'])
print("\nDataFrame:")
print(df)

# Печать первой строки DataFrame
print("\nПервая строка DataFrame:")
print(df.iloc[0])

# Вычитание первой строки из всего DataFrame (по столбцам)
print("\nРезультат вычитания первой строки из всего DataFrame (по столбцам):")
print(df.subtract(df.iloc[0], axis=1))

# Печать элементов первой строки с шагом 2 (т.е. столбцы 'a' и 'c')
print("\nЭлементы первой строки с шагом 2:")
print(df.iloc[0, ::2])

# Вычитание элементов первой строки с шагом 2 из всего DataFrame (по столбцам)
print("\nРезультат вычитания элементов первой строки с шагом 2 из всего DataFrame (по столбцам):")
print(df.subtract(df.iloc[0, ::2], axis=1))


Сгенерированный массив:
[[4 5 7 9]
 [0 1 8 9]
 [2 3 8 4]]

Первая строка массива:
[4 5 7 9]

Результат вычитания первой строки из всего массива:
[[ 0  0  0  0]
 [-4 -4  1  0]
 [-2 -2  1 -5]]

DataFrame:
   a  b  c  d
0  4  5  7  9
1  0  1  8  9
2  2  3  8  4

Первая строка DataFrame:
a    4
b    5
c    7
d    9
Name: 0, dtype: int64

Результат вычитания первой строки из всего DataFrame (по столбцам):
   a  b  c  d
0  0  0  0  0
1 -4 -4  1  0
2 -2 -2  1 -5

Элементы первой строки с шагом 2:
a    4
c    7
Name: 0, dtype: int64

Результат вычитания элементов первой строки с шагом 2 из всего DataFrame (по столбцам):
     a   b    c   d
0  0.0 NaN  0.0 NaN
1 -4.0 NaN  1.0 NaN
2 -2.0 NaN  1.0 NaN


In [14]:
# 5. На примере объектов DataFrame продемонстрируйте использование методов ffill() и bfill() 

data = {
    'A': [1, np.nan, 3, np.nan, 5],
    'B': [np.nan, 2, np.nan, 4, 5],
    'C': [1, 2, 3, 4, np.nan]
}
df = pd.DataFrame(data)

print(df)

df_ffill = df.ffill()
print(df_ffill)

df_bfill = df.bfill()
print(df_bfill)


     A    B    C
0  1.0  NaN  1.0
1  NaN  2.0  2.0
2  3.0  NaN  3.0
3  NaN  4.0  4.0
4  5.0  5.0  NaN
     A    B    C
0  1.0  NaN  1.0
1  1.0  2.0  2.0
2  3.0  2.0  3.0
3  3.0  4.0  4.0
4  5.0  5.0  4.0
     A    B    C
0  1.0  2.0  1.0
1  3.0  2.0  2.0
2  3.0  4.0  3.0
3  5.0  4.0  4.0
4  5.0  5.0  NaN
