In [ ]:
# Киселева Ксения 5030102\30002

In [7]:
## 1. Какие еще существуют коды типов?
"""
int (целое число) - представляет целые числа, например, 5, -3, 42.
float (число с плавающей запятой) - представляет числа с дробной частью, например, 3.14, -0.001, 2.0.
str (строка) - представляет последовательности символов, например, "Hello, World!", 'Python'.
bool (логический тип) - представляет логические значения, которые могут быть True или False.
list (список) - представляет упорядоченные изменяемые коллекции элементов, например, [1, 2, 3], ['a', 'b', 'c'].
tuple (кортеж) - представляет упорядоченные неизменяемые коллекции элементов, например, (1, 2, 3), ('a', 'b', 'c').
set (множество) - представляет неупорядоченные коллекции уникальных элементов, например, {1, 2, 3}, {'a', 'b', 'c'}.
dict (словарь) - представляет неупорядоченные коллекции пар "ключ-значение", например, {'name': 'Alice', 'age': 30}.
bytes (байты) - представляет последовательности байтов, например, b'hello'.
bytearray (массив байтов) - изменяемая последовательность байтов, например, bytearray(b'hello').
memoryview (представление памяти) - предоставляет доступ к внутренним данным объекта без копирования, например, memoryview(b'hello').
"""

'\nint (целое число) - представляет целые числа, например, 5, -3, 42.\nfloat (число с плавающей запятой) - представляет числа с дробной частью, например, 3.14, -0.001, 2.0.\nstr (строка) - представляет последовательности символов, например, "Hello, World!", \'Python\'.\nbool (логический тип) - представляет логические значения, которые могут быть True или False.\nlist (список) - представляет упорядоченные изменяемые коллекции элементов, например, [1, 2, 3], [\'a\', \'b\', \'c\'].\ntuple (кортеж) - представляет упорядоченные неизменяемые коллекции элементов, например, (1, 2, 3), (\'a\', \'b\', \'c\').\nset (множество) - представляет неупорядоченные коллекции уникальных элементов, например, {1, 2, 3}, {\'a\', \'b\', \'c\'}.\ndict (словарь) - представляет неупорядоченные коллекции пар "ключ-значение", например, {\'name\': \'Alice\', \'age\': 30}.\nbytes (байты) - представляет последовательности байтов, например, b\'hello\'.\nbytearray (массив байтов) - изменяемая последовательность байтов,

In [23]:
## 2. Напишите код, подобный приведенному выше, но с другим типом
import numpy as np
import array
import sys

al = array.array('f', [1.1, 2.2, 3.3])  # f - работаем только с float
print(sys.getsizeof(al))
print(type(al)) 

92
<class 'array.array'>


In [29]:
## 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1

arr = np.linspace(0, 1, 5) # если использовать np.arrange, то 1 не войдёт
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [37]:
## 4. Напишите код для создания массива с 5 равномерно распределенными случайными значениями в диапазоне от 0 до 1

arr = np.random.uniform(0, 1, 5)
print(arr)

[0.2277606  0.20536742 0.43754349 0.43872049 0.84648903]


In [39]:
## 5. Напишите код для создания массива с 5 нормально распределенными случайными значениями с мат. ожиданием = 0 и дисперсией 1

arr = np.random.normal(0, 1, 5)
print(arr)

[ 0.24692664 -0.31679866 -0.7950892  -0.6671632  -2.17982562]


In [45]:
## 6. Напишите код для создания массива с 5 случайнвми целыми числами в от [0, 10)

arr = np.random.randint(0, 10, 5)
print(arr)

[3 2 8 5 7]


In [71]:
## 7. Написать код для создания срезов массива 3 на 4
## - первые две строки и три столбца
## - первые три строки и второй столбец
## - все строки и столбцы в обратном порядке
## - второй столбец
## - третья строка

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr[:2,:3])
print(arr[:3,1:2])
print(arr[::-1,::-1])
print(arr[:,1:2])
print(arr[-1])

[[1 2 3]
 [5 6 7]]
[[ 2]
 [ 6]
 [10]]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 2]
 [ 6]
 [10]]
[ 9 10 11 12]


In [77]:
## 8. Продемонстрируйте, как сделать срез-копию

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

slice_copy = arr[0, :].copy()

slice_copy[0] = 99

print("Срез-копия:", slice_copy)
print("\nИсходный массив:", arr)

Срез-копия: [99  2  3]

Исходный массив: [[1 2 3]
 [4 5 6]]


In [81]:
## 9. Продемонстрируйте использование newaxis для получения вектора-столбца и вектора-строки

arr = np.array([1, 2, 3])
column_vector = arr[:, np.newaxis]
row_vector = arr[np.newaxis, :]

print("Исходный массив:", arr)
print("\nВектор-столбец:", column_vector)
print("\nВектор-строка:", row_vector)

Исходный массив: [1 2 3]

Вектор-столбец: [[1]
 [2]
 [3]]

Вектор-строка: [[1 2 3]]


In [87]:
## 10. Разберитесь, как работает метод dstack

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])
result = np.dstack((arr1, arr2))
print(result)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [117]:
## 11. Разберитесь, как работают методы split, vsplit, hsplit, dsplit

arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12]])

split_arr = np.split(arr, 2, axis=1)  # разделяем на 2 части по столбцам
print("split:", [x for x in split_arr])

vsplit_arr = np.vsplit(arr, 2)  # разделяем на 2 части по строкам
print("vsplit:", [x for x in vsplit_arr])

hsplit_arr = np.hsplit(arr, 6)  # разделяем на 6 частей по столбцам
print("hsplit:", [x for x in hsplit_arr])

arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

dsplit_arr = np.dsplit(arr_3d, 2)  # разделяем по глубине на 2 части
print("dsplit:", [x for x in dsplit_arr])

split: [array([[1, 2, 3],
       [7, 8, 9]]), array([[ 4,  5,  6],
       [10, 11, 12]])]
vsplit: [array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]
hsplit: [array([[1],
       [7]]), array([[2],
       [8]]), array([[3],
       [9]]), array([[ 4],
       [10]]), array([[ 5],
       [11]]), array([[ 6],
       [12]])]
dsplit: [array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


In [121]:
x = np.array([1, 2, 3, 4])

result_add = np.add(x, 2)                # сложение
result_multiply = np.multiply(x, 2)      # умножение
result_subtract = np.subtract(x, 2)      # вычитание
result_negate = np.negative(x)           # отрицание
result_divide = np.divide(x, 2)           # деление
result_floor_divide = np.floor_divide(x, 2)  # деление с округлением в меньшую сторону
result_power = np.power(x, 2)             # возведение в степень
result_mod = np.mod(x, 2)                 # остаток от деления
result_sqrt = np.sqrt(x)                  # квадратный корень

print(result_add)
print(result_multiply)
print(result_subtract)
print(result_negate)
print(result_divide)
print(result_floor_divide)
print(result_power)
print(result_mod)
print(result_sqrt)

[3 4 5 6]
[2 4 6 8]
[-1  0  1  2]
[-1 -2 -3 -4]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  4  9 16]
[1 0 1 0]
